# Generated by Django 2.2.6 on 2020-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.CharField(max_length=15),
        ),
    ]
