# Generated by Django 2.2.6 on 2020-03-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
