# Generated by Django 2.2.6 on 2020-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200320_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leaves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='taxes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
