# Generated by Django 2.2.6 on 2020-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200320_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
